inst1 <- data.frame(algo1=c(5329,
                            0,
                            0,
                            4994,
                            5582,
                            5479,
                            5179,
                            0,
                            5390,
                            5283,
                            0,
                            5289),
                    algo2=c(5329,
                            0,
                            0,
                            4994,
                            5582,
                            5479,
                            5179,
                            0,
                            5390,
                            5283,
                            0,
                            5289),
                    algo3=c(5329,
                            0,
                            0,
                            4994,
                            5582,
                            5479,
                            5179,
                            0,
                            5390,
                            5283,
                            0,
                            5289))

boxplot(inst1, names=c("BT", "B&B1", "B&B2"), ylim = c(4500, 5800))
title("Instância: nqp200.txt. Ótimo: Desconhecido")

